name: Test documentation build

on:
  pull_request:
    paths:
      - '**.py'
      - '**.ipynb'
      - '**.rst'
      - '**.md'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          init-shell: bash
          condarc: |
            channels:
              - conda-forge
            channel_priority: strict
          cache-environment: true

      - name: Install package (editable)
        shell: bash -l {0}
        run: |
          micromamba run -n TEST python -m pip install --upgrade pip
          micromamba run -n TEST python -m pip install -e . --no-deps --force-reinstall

      - name: Build documentation
        shell: bash -l {0}
        run: |
          set -e
          micromamba run -n TEST jupyter nbconvert --to notebook --execute notebooks/demo_instrument.ipynb --output=demo_instrument-output.ipynb --ExecutePreprocessor.allow_errors=True
          micromamba run -n TEST jupyter nbconvert --to notebook --execute notebooks/demo_mooring.ipynb --output=demo_mooring-output.ipynb --ExecutePreprocessor.allow_errors=True
          mv notebooks/*output.ipynb docs/source/
          pushd docs
          micromamba run -n TEST make clean html
          popd
